"""PDF report generator tool wrapped as a standard LangChain Tool using ReportLab Platypus."""

import logging
import time
import xml.sax.saxutils as saxutils
from pathlib import Path
from typing import Any, Dict, List, Optional

from backend.app.core.config import settings

REPORTS_DIR = settings.DATA_DIR / "reports"
logger = logging.getLogger("enterprise_ai.pdf_generator")


def _sanitize_markdown_for_reportlab(text_line: str) -> str:
    """Sanitizes markdown tags and XML entities into clean, formatted ReportLab XML strings."""
    if not text_line:
        return ""

    line = text_line.strip()

    if line.startswith("#"):
        line = line.lstrip("#").strip()

    if line.startswith("- ") or line.startswith("* "):
        line = f"&bull; {line[2:].strip()}"

    line = saxutils.escape(line)

    import re
    line = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", line)
    line = re.sub(r"\*(.*?)\*", r"<i>\1</i>", line)

    return line


def create_pdf_report(title: str, content: str, sources: Optional[List[str]] = None) -> Dict[str, Any]:
    """Generates a physical PDF document on disk using ReportLab Platypus flowables."""
    if not content or not content.strip():
        logger.error("PDF generation rejected: artifact content is empty!")
        raise ValueError("Cannot generate PDF: artifact content is empty.")

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    filename = f"report_{int(time.time())}.pdf"
    file_path = REPORTS_DIR / filename

    content_len = len(content.strip())
    preview = content.strip()[:200].replace("\n", " ")
    logger.info("Generating PDF: title=%r, content_length=%d, preview=%r", title, content_len, preview)

    try:
        from reportlab.lib import colors
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
        from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer

        doc = SimpleDocTemplate(
            str(file_path),
            pagesize=letter,
            rightMargin=50,
            leftMargin=50,
            topMargin=50,
            bottomMargin=50,
        )

        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Title"],
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=22,
            textColor=colors.HexColor("#1e293b"),
            alignment=0,
            spaceAfter=6,
        )

        meta_style = ParagraphStyle(
            "DocMeta",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#64748b"),
            spaceAfter=10,
        )

        body_style = ParagraphStyle(
            "DocBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#0f172a"),
            spaceAfter=8,
        )

        story = []

        clean_title_str = saxutils.escape(title.strip())
        story.append(Paragraph(clean_title_str, title_style))

        timestamp_str = time.strftime("%Y-%m-%d %H:%M:%S")
        source_str = f" | Sources: {', '.join(sources)}" if sources else ""
        story.append(Paragraph(f"Generated by Enterprise AI Assistant on {timestamp_str}{source_str}", meta_style))

        story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#cbd5e1"), spaceAfter=14))

        lines = content.split("\n")
        for raw_line in lines:
            if not raw_line.strip():
                story.append(Spacer(1, 6))
                continue

            cleaned_p = _sanitize_markdown_for_reportlab(raw_line)
            if cleaned_p:
                story.append(Paragraph(cleaned_p, body_style))

        doc.build(story)

    except Exception as err:
        logger.warning("ReportLab Platypus build error (%s), using Canvas fallback...", err)
        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas

        c = canvas.Canvas(str(file_path), pagesize=letter)
        width, height = letter

        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 50, title[:60])
        c.setFont("Helvetica", 9)
        c.drawString(50, height - 68, f"Generated on {time.strftime('%Y-%m-%d %H:%M:%S')}")
        c.line(50, height - 76, width - 50, height - 76)

        c.setFont("Helvetica", 10)
        y = height - 100
        for line in content.split("\n"):
            line_str = line.strip()
            if not line_str:
                y -= 12
                continue
            c.drawString(50, y, line_str[:90])
            y -= 14
            if y < 50:
                c.showPage()
                c.setFont("Helvetica", 10)
                y = height - 50
        c.save()

    if file_path.exists() and file_path.stat().st_size > 300:
        logger.info("PDF generated successfully: file=%s, size=%d bytes", filename, file_path.stat().st_size)
        return {
            "success": True,
            "filename": filename,
            "file_path": str(file_path),
            "size_bytes": file_path.stat().st_size,
            "message": f"PDF report '{filename}' successfully generated.",
        }
    else:
        raise RuntimeError(f"PDF generation failed or file size too small ({file_path.stat().st_size if file_path.exists() else 0} bytes).")
