"""Planner agent node for decomposing complex research requests."""

from typing import Any, Dict, List, Literal
from pydantic import BaseModel

from backend.app.agents.graph.state import GraphState
from backend.app.llm.llm_client import LLMClient


class ResearchTask(BaseModel):
    """Sub-task created by the Planner."""

    task_id: str
    task: str
    source: Literal["sql", "rag", "web"]


class ResearchPlan(BaseModel):
    """Complete research plan generated by the Planner."""

    tasks: List[ResearchTask]


async def planner_node(state: GraphState, llm_client: LLMClient) -> Dict[str, Any]:
    """
    Decomposes a complex research request into structured sub-tasks.
    Does NOT execute tools directly.
    """
    user_message = state.get("user_message", "")

    prompt = (
        "You are an expert Enterprise Research Planner.\n"
        "Decompose the complex user request into 2 to 4 independent sub-tasks.\n"
        "Available sources for sub-tasks:\n"
        "- 'sql': for database sales numbers, revenue, and transactional data.\n"
        "- 'rag': for internal enterprise documents, HR policies, remote work guidelines, or architecture guides.\n"
        "- 'web': for external web search, market trends, or AI industry developments.\n\n"
        f"User Request: {user_message}\n\n"
        "Respond ONLY with a valid JSON object matching this exact schema:\n"
        '{"tasks": [{"task_id": "task_1", "task": "Analyze Q1 company sales", "source": "sql"}, {"task_id": "task_2", "task": "Search recent AI developments", "source": "web"}]}'
    )

    try:
        raw_json = await llm_client.generate(prompt)
        clean_json = raw_json.replace("```json", "").replace("```", "").strip()
        plan = ResearchPlan.model_validate_json(clean_json)
        return {
            "research_plan": [task.model_dump() for task in plan.tasks]
        }
    except Exception:
        # Fallback plan if JSON generation fails
        fallback_tasks = [
            {"task_id": "task_1", "task": f"Research information for: {user_message}", "source": "web"},
            {"task_id": "task_2", "task": "Check internal documents for relevant context", "source": "rag"},
        ]
        return {"research_plan": fallback_tasks}
